### ISSUE TITLE
pinterest.com False Positive

### ISSUE THREAD

**Issue by p1r473** [ligyxy/Blocklist#8] opened 2020-04-05 17:39 UTC
Hi, this blocks social media site Pinterest.

**Comment by danny0838** [comment] 2020-04-05 17:48
I cannot reproduce the issue. Can you provide a URL of Pininterest page that is blocked?

**Comment by p1r473** [comment] 2020-04-05 22:36
You are blocking pinterest.com
https://github.com/gyli/Blocklist/blob/master/BLOCKLIST#L46468
This is a popular social media.

**Comment by gyli** [comment] 2020-04-05 22:41
@p1r473 Interesting, it comes back again! It's fixed now.

**Closed as completed** 2020-04-05 22:43 UTC

**Comment by p1r473** [comment] 2020-05-24 14:44
HI, looks like its back again @gyli 
I recommend adding a whitelist and then scripting the removal of the whitelist from your blocklist.
![image](https://user-images.githubusercontent.com/9235633/82756982-8edc6b80-9dab-11ea-8204-f6869009cd20.png)
