### ISSUE TITLE
imgur.com

### ISSUE THREAD

**Issue by p1r473** [ligyxy/Blocklist#9] opened 2020-05-24 16:28 UTC
This is a photo sharing social media site

**Comment by gyli** [comment] 2020-05-25 05:09
Thank you! The issue is fixed in commit https://github.com/gyli/Blocklist/commit/1ca386fefa8da7926674c6087941006c75aa8ce2.

**Closed as completed by gyli** 2020-05-25 05:09 UTC

**Comment by p1r473** [comment] 2022-09-09 15:33
@gyli this is still blocked.
![image](https://user-images.githubusercontent.com/9235633/189387498-d8cfa81f-31ea-4424-8470-6d9fcacf7b23.png)

**Comment by gyli** [comment] 2022-09-09 15:42
@p1r473 The old records accidentally went back since I restored files when changing dev machine but not using latest commit. It's now fixed and pushed https://github.com/gyli/Blocklist/commit/11001c3d093422ca0410f7da98627085428e26e8
